require 'transbank/sdk/oneclick/errors/oneclick_error'
require 'transbank/sdk/oneclick/inscription/inscription'
require 'transbank/sdk/oneclick/mall/base'
require 'transbank/sdk/oneclick/mall/mall_transaction'
require 'transbank/sdk/oneclick/mall/mall_inscription'