require 'transbank/sdk/oneclick/inscription/responses/mall_inscription_delete_response'
require 'transbank/sdk/oneclick/inscription/responses/mall_inscription_start_response'
require 'transbank/sdk/oneclick/inscription/responses/mall_inscription_finish_response'