require 'transbank/sdk/oneclick/errors/oneclick_error'
require 'transbank/sdk/oneclick/inscription/inscription'
require 'transbank/sdk/oneclick/mall/oneclick_mall'
require 'transbank/sdk/oneclick/mall_deferred/mall_deferred_transaction'
require 'transbank/sdk/oneclick/mall_deferred/mall_deferred_inscription'