require 'transbank/sdk/transaccion_completa/mall/responses/mall_transaction_commit_response'
require 'transbank/sdk/transaccion_completa/mall/responses/mall_transaction_status_response'
require 'transbank/sdk/transaccion_completa/mall/responses/mall_transaction_installments_response'
require 'transbank/sdk/transaccion_completa/mall/responses/mall_transaction_capture_response'
