require 'transbank/sdk/oneclick/mall/errors/oneclick_mall_errors'
require 'transbank/sdk/oneclick/mall/responses/oneclick_mall_responses'
require 'transbank/sdk/oneclick/mall/base'
require 'transbank/sdk/oneclick/mall/mall_inscription'
require 'transbank/sdk/oneclick/mall/mall_transaction'
