name: Ruby CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  sonar-cloud-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests with coverage
        run: bundle exec rake test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
