name: Ruby CI

on:
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' 

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: bundle exec rake test 

  sonar-cloud-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' 

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests with coverage
        run: bundle exec rake test 

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=transbankdevelopers
            -Dsonar.organization=TransbankDevelopers_transbank-sdk-ruby
            -Dsonar.ruby.coverage.reportPaths=coverage/.resultset.json
            -Dsonar.branch.name=${{ github.head_ref || github.ref_name }}
