name: Ruby CI

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' 

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: bundle exec rake test 

  sonar-cloud-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' 

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests with coverage
        run: bundle exec rake test 

      - name: Validar archivo de cobertura
        run: |
          echo "🔍 Verificando que coverage/.resultset.json exista..."
          if [ ! -f coverage/.resultset.json ]; then
            echo "❌ Error: El archivo coverage/.resultset.json no fue generado."
            echo "🧪 Asegúrate de que SimpleCov esté correctamente configurado."
            exit 1
          else
            echo "✅ Archivo de cobertura encontrado."
          fi        

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
